### Array_合并

In [122]:
import numpy as np
A = np.array([1,1,1])
B = np.array([2,2,2])
print(A,'\n')
print(B)

[1 1 1] 

[2 2 2]


#### 上下合并（vstack）

In [76]:
print(np.vstack((A,B)))
print()
# 属性探究
C = np.vstack((A,B))
print(A.shape,C.shape)

[[1 1 1]
 [2 2 2]]

(3,) (2, 3)


#### 左右合并(hstack)

In [77]:
print(np.hstack((A,B)))
print()
# 属性探究
D = np.hstack((A,B))
print(A.shape,D.shape)

[1 1 1 2 2 2]

(3,) (6,)


#### 特殊转置(是序列不是矩阵)

In [78]:
print(A)
print()
print(A[np.newaxis,:])
print()
print(A[np.newaxis,:].shape)
print()
print(A[:,np.newaxis])
print()
print(A[:,np.newaxis].shape)



[1 1 1]

[[1 1 1]]

(1, 3)

[[1]
 [1]
 [1]]

(3, 1)


#### 综合

In [120]:
A = np.array([1,1,1])[:,np.newaxis]
B = np.array([2,2,2])[:,np.newaxis]
C = np.vstack((A,B))
D = np.hstack((A,B))

print(A,'\n')
print(B,'\n')
print(C,'\n')
print(D,'\n')
print(A.shape,B.shape,C.shape,D.shape)

[[1]
 [1]
 [1]] 

[[2]
 [2]
 [2]] 

[[1]
 [1]
 [1]
 [2]
 [2]
 [2]] 

[[1 2]
 [1 2]
 [1 2]] 

(3, 1) (3, 1) (6, 1) (3, 2)


#### concatenate()

In [121]:
A = np.array([1,1,1])[:,np.newaxis]
B = np.array([2,2,2])[:,np.newaxis]

C = np.concatenate((A,B,B,A),axis=0)
print(C,'\n')

D = np.concatenate((A,B,B,A),axis=1)
print(D)

[[1]
 [1]
 [1]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [1]
 [1]
 [1]] 

[[1 2 2 1]
 [1 2 2 1]
 [1 2 2 1]]
