### Array_分割

#### 创建数据

In [2]:
import numpy as np

A = np.arange(12).reshape(3,4)
print(A)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


#### 纵向分割

In [5]:
print(np.split(A,2,axis = 1))

[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]


#### 横向分割


In [7]:
print(np.split(A,3,axis = 0))

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]


#### 错误分割

In [10]:
print(np.split(A,3,axis = 1))

ValueError: array split does not result in an equal division

#### 不等量分割

In [12]:
print(np.array_split(A,3, axis = 1))

[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2],
       [ 6],
       [10]]), array([[ 3],
       [ 7],
       [11]])]


#### 其他分割

In [18]:
print(np.vsplit(A,3)) #按行

print(np.hsplit(A,2)) #按列

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]
[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]
