### Copy & Deep Copy

#### =的赋值方式会带有关联性

In [6]:
import numpy as np

a = np.arange(4)
print(a)
b = a
c = a
d = b

[0 1 2 3]


In [9]:
a[0] = 11
print(a)

[11  1  2  3]


In [12]:
b is a
c is a
d is a

True

In [15]:
d[1:3] = [22,33]
print(a)
print(b)
print(c)

[11 22 33  3]
[11 22 33  3]
[11 22 33  3]


#### copy()的赋值方式没有关联性

In [29]:
y = np.arange(4)
x = y.copy()
print(x)
y[3] = 11
print(y)
print(x)

[0 1 2 3]
[ 0  1  2 11]
[0 1 2 3]
