### Numpy_基础运算2

In [6]:
import numpy as np
A = np.arange(0,12).reshape((3,4))
print(A)
print(np.argmin(A)) #最小值在数组中所在的位置
print(np.argmax(A)) #最大值在数组中所在的位置

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
0
11


#### 求矩阵均值

In [6]:
print(np.mean(A))
print(np.average(A))

7.5
7.5


In [17]:
print(A.mean())
print(np.median(A))

7.5
7.5


#### 求和

In [12]:
print(A.cumsum())

[ 2  5  9 14 20 27 35 44 54 65 77 90]


#### 累差运算 

In [18]:
print(np.diff(A))

[[1 1 1]
 [1 1 1]
 [1 1 1]]


#### Nonzero(得到非0元素的位置，第一个为行，第二个为列)

In [21]:
print(np.nonzero(A))

(array([0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2], dtype=int64), array([1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3], dtype=int64))


#### 排序

In [11]:
A1 = np.arange(12,0,-1).reshape(3,4)
print(A1)
print(np.sort(A1,axis=-1))

[[12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]
[[ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


#### 转置

In [13]:
print(np.transpose(A))
print(A.T)

[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


#### `clip((Array,Array_min,Array_max))

In [15]:
print(A)
print(np.clip(A,5,9))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[5 5 5 5]
 [5 5 6 7]
 [8 9 9 9]]
