### Numpy_基础运算

#### 一、基本运算

In [18]:
import numpy as np
a = np.array([10,20,30,40])
b = np.arange(4)
print(a)
print(b)

[10 20 30 40]
[0 1 2 3]


#### (1)加

In [6]:
c = a+b
print(c)

[10 21 32 43]


#### (2)乘(非数学定义)

In [17]:
c = a*b
print(c)

[  0  20  60 120]


#### (3)乘方

In [11]:
c=b**2
print(c)

[0 1 4 9]


#### (4)其他

In [13]:
c = 10*np.sin(a)
print(c)

[-5.44021111  9.12945251 -9.88031624  7.4511316 ]


In [14]:
print(b<3)     #判断相等时 使用 == 而不是 = 

[ True  True  True False]


#### 二、多行多维矩阵运算

In [16]:
a1 = np.array([[1,1],[0,1]])
b1 = np.arange(4).reshape((2,2))
print(a1)
print(b1)

[[1 1]
 [0 1]]
[[0 1]
 [2 3]]


#### (1)矩阵乘法

In [20]:
c_dot = np.dot(a1,b1)
print(c_dot)

[[2 4]
 [2 3]]


In [27]:
c_dot_2 = a.dot(b) 
print(a1.dot(b1))

[[2 4]
 [2 3]]


#### (2)sum()、min()、max()

In [46]:
a3 = np.random.random((2,4))          #类似投影的理解
print("a3=:",a3)
print("sum=:",np.sum(a3,axis = 0))    #0表示按列操作 1表示按行操作
print("min=:",np.min(a3,axis = 0))
print("max=:",np.max(a3,axis = 1))

a3=: [[0.93122347 0.11989898 0.66288183 0.46922245]
 [0.9276258  0.94506391 0.30276273 0.96764908]]
sum=: [1.85884927 1.0649629  0.96564457 1.43687154]
min=: [0.9276258  0.11989898 0.30276273 0.46922245]
max=: [0.93122347 0.96764908]
