### Numpy创建array

#### 关键字

    array：创建数组
    dtype:指定数据类型
    zeros：创建数据全0
    ones：创建数据全1
    empty：创建数据接近0
    arange:按范围创建数据
    linspace:创建线段

#### 创建数组

In [5]:
import numpy as np
a = np.array([2,23,4])
print(a)

[ 2 23  4]


#### 指定数据dtype(int,int32,float,float32)

In [7]:
a = np.array([2,23,4],dtype=np.int)
print(a.dtype)


int32


#### 创建特定数据

In [9]:
a = np.array([[2,23,4],[2,23,4]])
print(a)

[[ 2 23  4]
 [ 2 23  4]]


In [11]:
a = np.zeros((3,4))
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [14]:
a = np.ones((3,4))
print(a)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [26]:
a = np.empty((3,4)) #创建全空数组，每个值都接近于0, 实际情况存疑
print(a)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [25]:
a = np.arange(10,20,2)
print(a)

[10 12 14 16 18]


In [28]:
a = np.arange(12).reshape((3,4)) 
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [36]:
a = np.linspace(1,10,12) #开始端为1， 结束端为10， 分割成20个数据，生成线段 （间隔均匀的等差数列）
print(a)

[ 1.          1.81818182  2.63636364  3.45454545  4.27272727  5.09090909
  5.90909091  6.72727273  7.54545455  8.36363636  9.18181818 10.        ]


In [40]:
a = np.linspace(1,10,12).reshape((3,4))
print(a)

[[ 1.          1.81818182  2.63636364  3.45454545]
 [ 4.27272727  5.09090909  5.90909091  6.72727273]
 [ 7.54545455  8.36363636  9.18181818 10.        ]]
