### Numpy_索引

#### 一维索引

In [13]:
import numpy as np
A = np.arange(3,15)
print(A)

[ 3  4  5  6  7  8  9 10 11 12 13 14]


In [14]:
print(A[2])

5


In [29]:
A1 = A.reshape(3,4)
print(A1[2])

[[ 3  4  5  6]
 [ 7  8  9 10]
 [11 12 13 14]]

[11 12 13 14]


#### 二维索引

In [31]:
print(A1)
print()

print(A1[1][1])

[[ 3  4  5  6]
 [ 7  8  9 10]
 [11 12 13 14]]

8


In [23]:
print(A1[1,1])

8


In [33]:
print(A1[1,1:3])

[8 9]


#### 逐行打印

In [38]:
for row in A1:
    print(row)

[3 4 5 6]
[ 7  8  9 10]
[11 12 13 14]


#### 逐列打印

In [39]:
for column in A1.T:
    print(column)

[ 3  7 11]
[ 4  8 12]
[ 5  9 13]
[ 6 10 14]


#### 迭代输出(flatten 多维矩阵到一行，flat是一个迭代器，本身是object属性)

In [41]:
print(A.flatten())

[ 3  4  5  6  7  8  9 10 11 12 13 14]


In [44]:
for item in A:
    print(item)

3
4
5
6
7
8
9
10
11
12
13
14
